language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

before_script:
  - python ./setup.py install
  - pip install spinnaker_proxy
script: "py.test ."