language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

before_install:
  - pip install --upgrade pip setuptools wheel
  # SpiNNakerManchester internal dependencies; development mode
  - pip install -q --upgrade git+git://github.com/SpiNNakerManchester/SpiNNUtils.gt@$TRAVIS_BRANCH || pip install -q --upgrade git+git://github.com/SpiNNakerManchester/SpiNNUtils.git@master
  - pip install -q --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMachine.git@$TRAVIS_BRANCH || pip install -q --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMachine.git@master
  - pip install -q --upgrade git+git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git@$TRAVIS_BRANCH || pip install -q --upgrade git+git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git@master

install:
  - python ./setup.py install
  - pip install -r requirements-test.txt
  - pip install -r doc/doc_requirements.txt
  - pip install spinnaker_proxy

script:
  - py.test .
  # Code quality check
  - flake8 spinnman unittests
  - cd doc/source
  - sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia
