language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

sudo: required

before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386
  - wget https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q3-update/+download/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2
  - tar jxf gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-5_4-2016q3/bin/
  - echo $PATH
  - ldd gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-gcc
  - arm-none-eabi-gcc --version
  - wget https://github.com/SpiNNakerManchester/spinnaker_tools/releases/download/v3.1.0/spinnaker_tools_3.1.0.tar.gz
  - tar zxf spinnaker_tools_3.1.0.tar.gz
  - export SPINN_DIRS=$PWD/spinnaker_tools_3.1.0
  - cd $SPINN_DIRS
  - make
  - cd ..
  - cd c_models
  - make
  - cd ..
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMachine.git@master
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git@master
  - python ./setup.py install
  - pip install -r requirements-test.txt
  - pip install -r doc/doc_requirements.txt
  - pip install spinnaker_proxy
script:
  - py.test .
  # Code quality check
  - flake8 spinnman unittests
  - cd doc/source
  - sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia
