# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This workflow will install Python dependencies, run tests, lint and rat with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Actions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout SupportScripts
      uses: actions/checkout@v2
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support

    - name: Set GITHUB_BRANCH (merge)
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "GITHUB_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
    - name: Set GITHUB_BRANCH (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "GITHUB_BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: Checkout Spinnaker Dependencies
      run: |
        support/gitclone2.sh https://github.com/SpiNNakerManchester/SpiNNUtils.git
        support/gitclone2.sh https://github.com/SpiNNakerManchester/SpiNNMachine.git

    - name: Install -pip
      run: python -m pip install --upgrade pip

    - name: Install SpiNNUtils
      run: python setup.py install
      working-directory: SpiNNUtils

    - name: Install SpiNNMachine
      run: python setup.py install
      working-directory: SpiNNMachine

    - name: Install
      run: |
        python setup.py develop
        pip install -r requirements-test.txt
        pip install 'pylint<2.5'

    - name: Test with pytest
      run: |
        pytest unittests

    - name: Lint with flake8
      run: |
        # run flake8
        flake8 spinnman unittests
